from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import shlex
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

from .errors import ValidationError


GIB = 1024**3
LTX_ACCESS_URL = "https://huggingface.co/Lightricks/LTX-2.5"


@dataclass(frozen=True)
class ModelBundle:
    key: str
    repo_id: str
    directory: str
    allow_patterns: tuple[str, ...]
    gated: bool = False


LTX_FILES = (
    "diffusion_models/ltx-2.5-22b-dev-transformer-bf16.safetensors",
    "text_encoders/gemma4-12b-with-proj-ltx-2.5-bf16.safetensors",
    "vae/ltx-2.5-video-vae-bf16.safetensors",
    "vae/ltx-2.5-audio-vae-bf16.safetensors",
    "latent_upscale_models/ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
    "loras/ltx-2.5-22b-distilled-lora-450-bf16.safetensors",
)


MODEL_BUNDLES = (
    ModelBundle("ltx", "Lightricks/LTX-2.5", "ltx-2.5", LTX_FILES, gated=True),
    ModelBundle(
        "whisper",
        "Systran/faster-whisper-large-v3",
        "faster-whisper-large-v3",
        ("*.bin", "*.json", "*.txt"),
    ),
    ModelBundle(
        "qwen",
        "Qwen/Qwen2.5-VL-3B-Instruct",
        "qwen2.5-vl-3b-instruct",
        ("*.json", "*.safetensors", "*.model", "*.txt", "*.tiktoken", "LICENSE"),
    ),
)


def _atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        dir=path.parent,
        prefix=f".{path.name}.",
        delete=False,
    ) as handle:
        handle.write(text)
        temporary = Path(handle.name)
    os.replace(temporary, path)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _safe_models_root(value: str | Path) -> Path:
    root = Path(value).expanduser().resolve()
    if root == Path(root.anchor):
        raise ValidationError("The models root cannot be the filesystem root")
    return root


def _matches(bundle: ModelBundle, filename: str) -> bool:
    return any(fnmatch.fnmatch(filename, pattern) for pattern in bundle.allow_patterns)


def _remote_size(item: Any) -> int | None:
    direct = getattr(item, "size", None)
    if isinstance(direct, int):
        return direct
    lfs = getattr(item, "lfs", None)
    if isinstance(lfs, dict):
        value = lfs.get("size")
    else:
        value = getattr(lfs, "size", None)
    return value if isinstance(value, int) else None


def _remote_sha256(item: Any) -> str | None:
    lfs = getattr(item, "lfs", None)
    if isinstance(lfs, dict):
        value = lfs.get("sha256")
    else:
        value = getattr(lfs, "sha256", None)
    return value if isinstance(value, str) and len(value) == 64 else None


def _selected_remote_files(info: Any, bundle: ModelBundle) -> list[Any]:
    files = [item for item in info.siblings if _matches(bundle, item.rfilename)]
    names = {item.rfilename for item in files}
    if bundle.key == "ltx":
        missing = [name for name in LTX_FILES if name not in names]
        if missing:
            raise ValidationError(
                f"The official LTX repository no longer contains required files: {missing}"
            )
    if not files:
        raise ValidationError(f"No required files were found in {bundle.repo_id}")
    return files


def _existing_parent(path: Path) -> Path:
    candidate = path
    while not candidate.exists() and candidate != candidate.parent:
        candidate = candidate.parent
    return candidate


def build_model_env(models_root: Path, installed: Iterable[str]) -> str:
    installed_keys = set(installed)
    root = models_root.resolve()
    lines = [
        "# Generated by zolex-music-video install-models.",
        "# No credentials are stored in this file.",
    ]
    if "ltx" in installed_keys:
        ltx = root / "ltx-2.5"
        values = {
            "LTX_TRANSFORMER_PATH": ltx / LTX_FILES[0],
            "LTX_TEXT_ENCODER_PATH": ltx / LTX_FILES[1],
            "LTX_VIDEO_VAE_PATH": ltx / LTX_FILES[2],
            "LTX_AUDIO_VAE_PATH": ltx / LTX_FILES[3],
            "LTX_SPATIAL_UPSAMPLER_PATH": ltx / LTX_FILES[4],
            "LTX_DISTILLED_LORA_PATH": ltx / LTX_FILES[5],
        }
        lines.extend(f"{key}={shlex.quote(str(path))}" for key, path in values.items())
    if "whisper" in installed_keys:
        lines.extend(
            (
                f"ZOLEX_TRANSCRIPTION_MODEL={shlex.quote(str(root / 'faster-whisper-large-v3'))}",
                "ZOLEX_TRANSCRIPTION_BACKEND=faster_whisper",
            )
        )
    if "qwen" in installed_keys:
        lines.extend(
            (
                f"ZOLEX_REFERENCE_VISION_MODEL={shlex.quote(str(root / 'qwen2.5-vl-3b-instruct'))}",
                "ZOLEX_REFERENCE_VISION_BACKEND=qwen",
                "ZOLEX_REFERENCE_VISION_LOCAL_FILES_ONLY=true",
            )
        )
    return "\n".join(lines) + "\n"


def install_required_models(
    *,
    models_root: str | Path,
    skip: Iterable[str] = (),
    max_workers: int = 4,
    verify_sha256: bool = True,
    dry_run: bool = False,
    env_output: str | Path | None = None,
) -> dict[str, Any]:
    if not (1 <= max_workers <= 16):
        raise ValidationError("Model download max_workers must be between 1 and 16")
    root = _safe_models_root(models_root)
    skip_keys = set(skip)
    unknown = skip_keys - {bundle.key for bundle in MODEL_BUNDLES}
    if unknown:
        raise ValidationError(f"Unknown model groups to skip: {sorted(unknown)}")
    bundles = [bundle for bundle in MODEL_BUNDLES if bundle.key not in skip_keys]
    if not bundles:
        raise ValidationError("At least one model group must be selected")

    try:
        from huggingface_hub import HfApi, get_hf_file_metadata, get_token, hf_hub_url, snapshot_download
        from huggingface_hub.utils import GatedRepoError, HfHubHTTPError
    except ImportError as exc:
        raise ValidationError(
            "Model installation requires the 'models' extra: python -m pip install '.[models]'"
        ) from exc

    token = get_token()
    if any(bundle.gated for bundle in bundles) and not token:
        raise ValidationError(
            "LTX-2.5 is gated. Accept its terms at "
            f"{LTX_ACCESS_URL}, then run 'hf auth login' or set HF_TOKEN before retrying."
        )
    api = HfApi(token=token)
    preflight: list[tuple[ModelBundle, Any, list[Any]]] = []
    try:
        for bundle in bundles:
            info = api.model_info(bundle.repo_id, revision="main", files_metadata=True)
            files = _selected_remote_files(info, bundle)
            if bundle.gated:
                get_hf_file_metadata(
                    hf_hub_url(bundle.repo_id, filename=LTX_FILES[0], revision=info.sha),
                    token=token,
                )
            preflight.append((bundle, info, files))
    except GatedRepoError as exc:
        raise ValidationError(
            "The Hugging Face account cannot access LTX-2.5 yet. Accept the model terms at "
            f"{LTX_ACCESS_URL}, verify the account token, and retry."
        ) from exc
    except HfHubHTTPError as exc:
        raise ValidationError(f"Hugging Face model preflight failed: {exc}") from exc

    expected_bytes = 0
    required_bytes = 0
    plans: list[dict[str, Any]] = []
    for bundle, info, files in preflight:
        target = root / bundle.directory
        bundle_bytes = 0
        bundle_required = 0
        for item in files:
            size = _remote_size(item)
            if size is not None:
                bundle_bytes += size
                local = target / item.rfilename
                if not local.is_file() or local.stat().st_size != size:
                    bundle_required += size
        expected_bytes += bundle_bytes
        required_bytes += bundle_required
        plans.append(
            {
                "group": bundle.key,
                "repo_id": bundle.repo_id,
                "revision": info.sha,
                "target": str(target),
                "file_count": len(files),
                "expected_bytes": bundle_bytes,
                "required_download_bytes": bundle_required,
            }
        )

    if dry_run:
        return {
            "status": "dry_run",
            "models_root": str(root),
            "expected_bytes": expected_bytes,
            "required_download_bytes": required_bytes,
            "models": plans,
        }

    root.mkdir(parents=True, exist_ok=True)
    free_bytes = shutil.disk_usage(_existing_parent(root)).free
    required_with_margin = required_bytes + max(2 * GIB, round(required_bytes * 0.05))
    if free_bytes < required_with_margin:
        raise ValidationError(
            f"Insufficient free disk space: need approximately {required_with_margin} bytes "
            f"including safety margin, but only {free_bytes} bytes are available"
        )

    installed_models: list[dict[str, Any]] = []
    for bundle, info, files in preflight:
        target = root / bundle.directory
        target.mkdir(parents=True, exist_ok=True)
        try:
            snapshot_download(
                repo_id=bundle.repo_id,
                revision=info.sha,
                local_dir=target,
                allow_patterns=list(bundle.allow_patterns),
                token=token,
                max_workers=max_workers,
            )
        except GatedRepoError as exc:
            raise ValidationError(
                f"LTX-2.5 download was denied. Accept its terms at {LTX_ACCESS_URL} and retry."
            ) from exc
        except HfHubHTTPError as exc:
            raise ValidationError(f"Download failed for {bundle.repo_id}: {exc}") from exc

        verified_files: list[dict[str, Any]] = []
        for item in files:
            local = target / item.rfilename
            if not local.is_file():
                raise ValidationError(f"Downloaded model file is missing: {local}")
            expected_size = _remote_size(item)
            actual_size = local.stat().st_size
            if expected_size is not None and actual_size != expected_size:
                raise ValidationError(
                    f"Model size mismatch for {local}: expected {expected_size}, got {actual_size}"
                )
            expected_sha = _remote_sha256(item)
            actual_sha = _sha256(local) if verify_sha256 and expected_sha else None
            if expected_sha and actual_sha != expected_sha:
                raise ValidationError(f"SHA-256 mismatch for downloaded model file: {local}")
            verified_files.append(
                {
                    "relative_path": item.rfilename,
                    "size_bytes": actual_size,
                    "expected_sha256": expected_sha,
                    "verified_sha256": actual_sha,
                }
            )
        installed_models.append(
            {
                "group": bundle.key,
                "repo_id": bundle.repo_id,
                "revision": info.sha,
                "target": str(target),
                "files": verified_files,
            }
        )

    env_path = Path(env_output).expanduser().resolve() if env_output else root / "zolex-models.env"
    manifest_path = root / "zolex-model-install-manifest.json"
    manifest = {
        "schema_version": 1,
        "models_root": str(root),
        "credentials_stored": False,
        "verification": "remote size plus LFS SHA-256" if verify_sha256 else "remote size",
        "models": installed_models,
        "environment_file": str(env_path),
    }
    _atomic_write_text(env_path, build_model_env(root, [item["group"] for item in installed_models]))
    _atomic_write_text(manifest_path, json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return {
        "status": "complete",
        "models_root": str(root),
        "manifest": str(manifest_path),
        "environment_file": str(env_path),
        "models": plans,
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Download and verify ZolexAI model weights")
    parser.add_argument("--models-root", type=Path, default=Path("/models"))
    parser.add_argument("--max-workers", type=int, default=4)
    parser.add_argument("--skip-ltx", action="store_true")
    parser.add_argument("--skip-whisper", action="store_true")
    parser.add_argument("--skip-qwen", action="store_true")
    parser.add_argument("--size-only", action="store_true", help="Skip the additional local LFS SHA-256 pass")
    parser.add_argument("--dry-run", action="store_true", help="Check access and disk requirements without downloading")
    parser.add_argument("--env-output", type=Path)
    return parser


def main() -> None:
    args = _parser().parse_args()
    skip = [
        key
        for key, enabled in (
            ("ltx", args.skip_ltx),
            ("whisper", args.skip_whisper),
            ("qwen", args.skip_qwen),
        )
        if enabled
    ]
    result = install_required_models(
        models_root=args.models_root,
        skip=skip,
        max_workers=args.max_workers,
        verify_sha256=not args.size_only,
        dry_run=args.dry_run,
        env_output=args.env_output,
    )
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
