"""initial schema

Revision ID: b066c7ac256b
Revises: 
Created: 2026-08-11 12:39:01.700239
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b066c7ac256b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('plan_code', sa.String(length=40), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('worker_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('online', 'busy', 'offline', name='workerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('runtime', sa.String(length=40), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('max_concurrency', sa.SmallInteger(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_nodes')),
    sa.UniqueConstraint('name', name=op.f('uq_worker_nodes_name'))
    )
    op.create_index('ix_worker_nodes_status_heartbeat', 'worker_nodes', ['status', 'last_heartbeat_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('video', 'image', 'audio', name='assetkind', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('upload', 'generated', name='assetsource', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='assetstatus', native_enum=False, length=32), nullable=False),
    sa.Column('storage_bucket', sa.String(length=120), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_assets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('storage_bucket', 'storage_key', name='uq_assets_storage_location')
    )
    op.create_index('ix_assets_user_created', 'assets', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_assets_user_kind_created', 'assets', ['user_id', 'kind', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_assets_user_status', 'assets', ['user_id', 'status'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'assigned', 'preparing', 'generating', 'post_processing', 'uploading', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('stage_hint', sa.String(length=200), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error_code', sa.Enum('validation_failed', 'not_found', 'conflict', 'unauthorized', 'forbidden', 'rate_limited', 'concurrency_limit_reached', 'idempotency_key_reused', 'unsupported_workflow', 'unsupported_parameter', 'missing_required_input', 'asset_not_ready', 'unsupported_media_type', 'file_too_large', 'lease_lost', 'max_attempts_exceeded', 'generation_failed', 'storage_unavailable', 'internal_error', name='errorcode', native_enum=False, length=48), nullable=True),
    sa.Column('error_message', sa.String(length=400), nullable=True),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('lease_token', sa.UUID(), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('last_event_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_generation_jobs_attempt_count_positive')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_generation_jobs_progress_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_generation_jobs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_nodes.id'], name=op.f('fk_generation_jobs_worker_id_worker_nodes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index('ix_generation_jobs_claimable', 'generation_jobs', ['created_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_generation_jobs_lease_expiry', 'generation_jobs', ['lease_expires_at'], unique=False, postgresql_where=sa.text('lease_expires_at IS NOT NULL'))
    op.create_index('ix_generation_jobs_user_created', 'generation_jobs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_generation_jobs_user_status_created', 'generation_jobs', ['user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_generation_jobs_user_workflow_created', 'generation_jobs', ['user_id', 'workflow_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_generation_jobs_user_idempotency', 'generation_jobs', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('generation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('status', 'progress', 'completed', 'failed', 'cancelled', name='eventtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'assigned', 'preparing', 'generating', 'post_processing', 'uploading', 'completed', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], name=op.f('fk_generation_events_job_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_events')),
    sa.UniqueConstraint('job_id', 'seq', name='uq_generation_events_job_seq')
    )
    op.create_index('ix_generation_events_job_seq', 'generation_events', ['job_id', 'seq'], unique=False)
    op.create_table('generation_job_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_generation_job_inputs_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], name=op.f('fk_generation_job_inputs_job_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_job_inputs')),
    sa.UniqueConstraint('job_id', 'role', name='uq_generation_job_inputs_job_role')
    )
    op.create_index('ix_generation_job_inputs_job', 'generation_job_inputs', ['job_id'], unique=False)
    op.create_table('generation_job_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('video', 'image', 'audio', name='assetkind', native_enum=False, length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_generation_job_outputs_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], name=op.f('fk_generation_job_outputs_job_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_job_outputs'))
    )
    op.create_index('ix_generation_job_outputs_job', 'generation_job_outputs', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generation_job_outputs_job', table_name='generation_job_outputs')
    op.drop_table('generation_job_outputs')
    op.drop_index('ix_generation_job_inputs_job', table_name='generation_job_inputs')
    op.drop_table('generation_job_inputs')
    op.drop_index('ix_generation_events_job_seq', table_name='generation_events')
    op.drop_table('generation_events')
    op.drop_index('uq_generation_jobs_user_idempotency', table_name='generation_jobs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_generation_jobs_user_workflow_created', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_user_status_created', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_user_created', table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_lease_expiry', table_name='generation_jobs', postgresql_where=sa.text('lease_expires_at IS NOT NULL'))
    op.drop_index('ix_generation_jobs_claimable', table_name='generation_jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('generation_jobs')
    op.drop_index('ix_assets_user_status', table_name='assets')
    op.drop_index('ix_assets_user_kind_created', table_name='assets')
    op.drop_index('ix_assets_user_created', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_worker_nodes_status_heartbeat', table_name='worker_nodes')
    op.drop_table('worker_nodes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
